modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="no_more_map_in_offhand"
version="${version}"
displayName="No More Map in Offhand"
displayURL="https://www.curseforge.com/members/madgique/projects"
authors="Madgique"
description='''No More Map in Offhand - Display maps from accessory slots without holding them'''
logoFile = "icon.png"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.no_more_map_in_offhand]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.no_more_map_in_offhand]]
    modId="architectury"
    mandatory=true
    versionRange="[9.2.14,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.no_more_map_in_offhand]]
    modId="curios"
    mandatory=true
    versionRange="[5.9.0,)"
    ordering="NONE"
    side="BOTH"


